import type { Destination } from "@/lib/engine/types";

export const destinations: Destination[] = [
  {
    slug: "munich",
    name: "Munich",
    dates: "Sept 6–8",
    dayIds: [2, 3, 4],
    lodging: "The Wombat Hostel",
    transportIn: "Overnight flight from Kansas City, then the airport train to München Hbf.",
    transportOut: "Train to Innsbruck on the Eurail pass.",
    photo: "/photos/wombat-exterior.jpg",
    photoAlt: "The street entrance of Wombat's City Hostel Munich Hauptbahnhof.",
    summary: "The first city. Two nights after a long flight, then the train south.",
    lngLat: [11.575, 48.137],
  },
  {
    slug: "innsbruck",
    name: "Innsbruck",
    dates: "Sept 8–9",
    dayIds: [4, 5],
    lodging: "Montagu Hostel",
    transportIn: "Train from Munich.",
    transportOut: "Morning train to Bolzano, then bus to Ortisei.",
    photo: "/photos/innsbruck.jpg",
    photoAlt: "Innsbruck along the Inn, mountains standing over the old town.",
    summary: "One night in the valley before the bus into the Dolomites.",
    lngLat: [11.404, 47.269],
  },
  {
    slug: "ortisei",
    name: "Ortisei",
    dates: "Sept 9",
    dayIds: [5],
    lodging: "We pass through; the night is up at Rifugio Resciesa.",
    transportIn: "Bus from Bolzano.",
    transportOut: "Onto the trail toward Rifugio Resciesa.",
    photo: "/photos/ortisei.jpg",
    photoAlt: "Ortisei in Val Gardena, the village at the foot of the ridge.",
    summary: "The last town before the huts. Rail ends here; the trail begins.",
    lngLat: [11.6717, 46.5761],
  },
  {
    slug: "dolomites",
    name: "Dolomites",
    dates: "Sept 9–12",
    dayIds: [5, 6, 7, 8],
    lodging: "Rifugio Resciesa, Rifugio Firenze, then Val di Fassa (lodging TBD)",
    transportIn: "From Ortisei onto the ridge.",
    transportOut: "Bus over Passo Costalunga to Bolzano, then train to Venice.",
    photo: "/photos/dolomites.jpg",
    photoAlt: "The Odle peaks from Seceda, limestone spires above the Val Gardena ridge.",
    summary: "Two hut nights, a summit morning on Seceda, then down to a spa in Val di Fassa before the train out.",
    stops: ["Rifugio Resciesa", "Rifugio Firenze", "Seceda"],
    lngLat: [11.7, 46.595],
  },
  {
    slug: "venice",
    name: "Venice",
    dates: "Sept 13–14",
    dayIds: [9, 10],
    lodging: "Still to be decided",
    transportIn: "Train from Bolzano via Verona, arriving Sept 12.",
    transportOut: "Flight to Kansas City.",
    photo: "/photos/venice.jpg",
    photoAlt: "A Venice canal at water level, looking toward a bridge.",
    summary: "The last city. An open day, then home.",
    lngLat: [12.3208, 45.4413],
  },
];
