import type { DetailRecord } from "@/lib/engine/types";

export const details: DetailRecord[] = [
  {
    slug: "flight-mci-muc",
    dayId: 1,
    title: "Kansas City to Munich",
    kind: "flight",
    body: "Departs MCI at 1:45 PM on Sept 5. Overnight, 12+ hours. Arrive Munich around 10:00 the next morning.",
  },
  {
    slug: "the-plane",
    dayId: 1,
    title: "The plane",
    kind: "stay",
    body: "The first night is the crossing. Sleep on the plane.",
  },
  {
    slug: "airport-train",
    dayId: 2,
    title: "Airport train to München Hbf",
    kind: "train",
    body: "From MUC into the city. Tickets at the airport.",
  },
  {
    slug: "wombat-hostel",
    dayId: 2,
    title: "The Wombat Hostel",
    kind: "stay",
    body: "Two nights in Munich, about €30/night pp, near the Hauptbahnhof.",
    todo: "Book 1–2 months out",
  },
  {
    slug: "english-garden",
    dayId: 3,
    title: "Englischer Garten",
    kind: "note",
    body: "A Valhalla-routed 2.2 km walk from Eisbachwelle to Kleinhesseloher See, with stops at the Monopteros and Chinesischer Turm. Allow about 30 minutes of moving time, plus however long the views, beer garden, and lake keep you.",
    extra: "The Monopteros is the skyline stop; the Chinese Tower is the beer-garden stop; the Seehaus sits at the lake finish.",
  },
  {
    slug: "hofbrauhaus",
    dayId: 3,
    title: "Hofbräuhaus am Platzl",
    kind: "note",
    body: "The royal brewery was founded by Duke Wilhelm V in 1589, opened as a public tavern in 1828, and rebuilt into today's beer hall in 1896–97. The ground-floor Schwemme and Wirtsgarten use free seating; reservations are for the upstairs Bräustüberl and start with groups of four.",
    extra: "Platzl 9 · currently open daily 11:00–00:00 · kitchen to 22:00 · last drinks 23:30.",
  },
  {
    slug: "train-munich-innsbruck",
    dayId: 4,
    title: "Munich to Innsbruck",
    kind: "train",
    body: "Eurail day. München Hbf to Innsbruck, about 1h50.",
  },
  {
    slug: "montagu-hostel",
    dayId: 4,
    title: "Montagu Hostel",
    kind: "stay",
    body: "One night in Innsbruck, about €30/night pp.",
    todo: "Book 1–2 months out",
  },
  {
    slug: "train-innsbruck-bolzano",
    dayId: 5,
    title: "Innsbruck to Bolzano",
    kind: "train",
    body: "Morning train on the Eurail pass, down the Brenner.",
  },
  {
    slug: "bus-bolzano-ortisei",
    dayId: 5,
    title: "Bolzano to Ortisei",
    kind: "bus",
    body: "A 35.9 km Valhalla street route from Bolzano station into Val Gardena, following the SS12 to Ponte Gardena and the SS242 into Ortisei. The last motorized leg before the huts.",
  },
  {
    slug: "rifugio-resciesa",
    dayId: 5,
    title: "Rifugio Resciesa",
    kind: "stay",
    body: "First hut night, above Ortisei. The mapped approach follows the Resciesa funicular and trail 35 to the hut.",
  },
  {
    slug: "rifugio-firenze",
    dayId: 6,
    title: "Rifugio Firenze",
    kind: "stay",
    body: "Second hut night, after hiking across the Odle group from Resciesa.",
  },
  {
    slug: "seceda-summit",
    dayId: 7,
    title: "Seceda",
    kind: "hike",
    body: "Up from Rifugio Firenze through Val Cisles to the summit ridge, ~2,519 m, looking straight at the Odle group.",
  },
  {
    slug: "down-to-ortisei",
    dayId: 7,
    title: "Seceda to Ortisei",
    kind: "hike",
    body: "The Seceda cable car runs down to Ortisei — a fast, scenic descent instead of retracing the climb on foot.",
  },
  {
    slug: "to-val-di-fassa",
    dayId: 7,
    title: "Ortisei to Val di Fassa",
    kind: "bus",
    body: "A 40.8 km street route over Passo Sella and down through Canazei into Val di Fassa, ending at QC Terme Dolomiti in Pozza di Fassa.",
  },
  {
    slug: "qc-terme-dolomiti",
    dayId: 7,
    title: "QC Terme Dolomiti",
    kind: "note",
    body: "A spa afternoon in Pozza di Fassa — indoor and outdoor pools with Dolomite views. A different kind of hut day.",
  },
  {
    slug: "val-di-fassa-night",
    dayId: 7,
    title: "Val di Fassa, first night",
    kind: "stay",
    body: "Where exactly in the valley is still open — Pozza, Canazei, and Vigo di Fassa are all in range of the spa.",
    todo: "Book a place to stay in Val di Fassa",
  },
  {
    slug: "bus-fassa-bolzano",
    dayId: 8,
    title: "Val di Fassa to Bolzano",
    kind: "bus",
    body: "A 40.9 km street route over Passo Costalunga (Karerpass) and down through Nova Levante into Bolzano — the way out of the mountains.",
  },
  {
    slug: "venice-first-night",
    dayId: 8,
    title: "First night in Venice",
    kind: "stay",
    body: "The train from Bolzano gets in with the evening ahead. Lodging for the night of the 12th is still open.",
    todo: "Book Venice lodging",
  },
  {
    slug: "train-bolzano-venice",
    dayId: 8,
    title: "Bolzano to Venezia Santa Lucia",
    kind: "train",
    body: "About 4 hours on the Eurail pass, via Trento, Rovereto, and Verona, then east across the plain to Venice.",
  },
  {
    slug: "venice-lodging",
    dayId: 9,
    title: "Venice lodging",
    kind: "stay",
    body: "Still to be decided. The night slot is a TODO, not a missing page.",
    todo: "Book Venice lodging",
  },
  {
    slug: "flight-vce-mci",
    dayId: 10,
    title: "Venice to Kansas City",
    kind: "flight",
    body: "Fly Venice → MCI on Sept 14. Confirmation details still to be added.",
  },
  {
    slug: "flight-home",
    dayId: 10,
    title: "Homeward",
    kind: "stay",
    body: "The trip ends in the air, the same way it began.",
  },
];
